version: 2.1
orbs:
  win: circleci/windows@5.0 #orb version
jobs:
 build:
   executor:
      name: win/default
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
workflows:
  build-api:
    jobs:
      - build