version: 2.1
orbs:
  node: circleci/windows@5 #orb version
jobs:
 build:
   executor:
      name: win/default
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run
workflows:
  build-api:
    jobs:
      - build